#page title
page_title                                : KLUCK                                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://play.google.com/store/apps/details?id=bum.wee.kluckapp                               # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=bum.wee.kluckapp                               # Enter Google Play Store URL.
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : KLUCK                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : KLuck is very simple and brings you the analyzed lucky number.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : KLuck
your_link                                 : https://play.google.com/store/apps/details?id=bum.wee.kluckapp
your_city                                 : Vietnam
email_address                             : kluck.web.app@gmail.com
facebook_username                         :                                           
instagram_username                        : KLuck
twitter_username                          : KLuck
github_username                           : KLuck
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Generate lucky numbers.
    description                           : Analyzes the number and provides 6 random numbers.
    fontawesome_icon_name                 : magic
    
  - title                                 : Lucky number storage function.
    description                           : You can save the lucky number and view it in your own library, and delete it.
    fontawesome_icon_name                 : mobile

  - title                                 : You can see the latest winning numbers.
    description                           : From the first winning amount to the latest winning amount, you can view and analyze it.
    fontawesome_icon_name                 : play-circle

  - title                                 : Generate random numbers by applying fixed and excluded numbers.
    description                           : You can make a random number including the number you specify, and it is possible to generate a lucky number with the rest of the numbers except for the number you excluded.
    fontawesome_icon_name                 : sync

  - title                                 : Daily attendance points paid.
    description                           : By paying attendance points every day, you can take a bulletin board and a more detailed analysis number later.
    fontawesome_icon_name                 : adjust
  
  - title                                 : My page.
    description                           : On my page, you can view the points paid every day and receive relevant guidance.
    fontawesome_icon_name                 : star

  - title                                 : Community.
    description                           : You can see and write various articles in the community. Bulletin boards of various categories will be added in the future.
    fontawesome_icon_name                 : link

  - title                                 : Customer Inquiry.
    description                           : Complaints and requests can be received through customer inquiries, which will be updated immediately.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Advertising.
    description                           : Through advertising inquiries, you can promote restaurants and sites with main advertisements or button links.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown